/*
 * generated by Xtext 2.9.2
 */
package org.example.domainmodel.scoping

import org.eclipse.xtext.scoping.Scopes
import org.eclipse.xtext.scoping.IScope


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class DomainmodelScopeProvider extends AbstractDomainmodelScopeProvider {

}
