/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.example.domainmodel.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.example.domainmodel.services.DomainmodelGrammarAccess;

@SuppressWarnings("all")
public class DomainmodelSyntacticSequencer extends AbstractSyntacticSequencer {

	protected DomainmodelGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Entity_PrivateKeyword_1_q;
	protected AbstractElementAlias match_Entity_PublicKeyword_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (DomainmodelGrammarAccess) access;
		match_Entity_PrivateKeyword_1_q = new TokenAlias(false, true, grammarAccess.getEntityAccess().getPrivateKeyword_1());
		match_Entity_PublicKeyword_0_q = new TokenAlias(false, true, grammarAccess.getEntityAccess().getPublicKeyword_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Entity_PrivateKeyword_1_q.equals(syntax))
				emit_Entity_PrivateKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entity_PublicKeyword_0_q.equals(syntax))
				emit_Entity_PublicKeyword_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'private'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'public'? (ambiguity) 'entity' name=ID
	 */
	protected void emit_Entity_PrivateKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'public'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'private'? 'entity' name=ID
	 */
	protected void emit_Entity_PublicKeyword_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
